project_name: switchbot-meter
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    main: ./main.go
    binary: switchbot-meter
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
archives:
  - wrap_in_directory: true
    files:
      - CREDITS
      - LICENSE
      - README.md
release:
  draft: true
